[phases.setup]
aptPkgs = ['postgresql-client']

[phases.build]
cmds = [
  'npm install',
  'npm run build --workspace @mawu/web'
]

[phases.deploy]
cmds = [
  'npm run db:push'
]

[start]
cmd = 'npm run dev:server'
