[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --include=dev"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "API_PORT=${PORT:-3001} NODE_ENV=${NODE_ENV:-production} npm run start"
